### ISSUE TITLE
need version and date as entry label for each CHANGELOG.md entry, not commit hash number

### ISSUE THREAD

**Issue by faddah** [lalitkapoor/github-changes#49]
hi

i really like your github-changes module for auto-generating a CHANGELOG.md for my github repository. really neat.

one thing -- i want the title tags for each entry to be the date( and versioning number. instead, what i get is the hash number from each commit as title tag (hyperlinked to entry in github), like so:

```

upcoming (2015/02/27 03:52 +00:00)

* b9d2991 using npm module github-changes, auto-generated & added CHANGELOG.md. also updated README.md and package.json to reflect this info. v0.1.3. (@faddah)
* eb30d34 Put in appropriate line breaks in console.log() print outs. Error messages from servers forecast.io and geonames.org now correct and consistent. Updated README.md. Regenerated package.json with npm init. (@faddah)
* dbc400c minor edit changes to README.md - slice[2] -> slice(2) where applicable. (@faddah)
...

```

... etc. what i would prefer is what i see generated in your README.md example, like so:

```

## Change Log

### v2.3.3 (2014/02/20 00:22 +00:00)
- [#83](https://github.com/goodybag/mongo-sql/pull/83) Buffer not defined in browser (@jrf0110)

### v2.3.2 (2014/02/19 23:54 +00:00)
- [#82](https://github.com/goodybag/mongo-sql/pull/82) Preserve Buffer query values. (@alexmingoia)

### v2.3.1 (2014/02/08 23:01 +00:00)
- [#81](https://github.com/goodybag/mongo-sql/pull/81) Casts + JSON derefs are malformed during the automated quoting (@jrf0110)

```

... like that.

i have done the command line call in my local git repository the way i think it should be done to get this, which is:

```bash

$ github-changes -o faddah -r node-forecast-io-serve -a -t "Change Log - node-forecast-io-serve"

```

... but that just gives me the result i'm seeing at the top above. how do i do it so it gives me the version and date of the commit? please advise and i thank you in advance for your help here.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by lalitkapoor** [comment]
@faddah sorry for the late reply. Take a look at my release script for how I do it - https://github.com/lalitkapoor/github-changes/blob/master/release.sh
