### ISSUE TITLE
Feature request: Include upcoming changes in --between-tags

### ISSUE THREAD

**Issue by grEvenX** [lalitkapoor/github-changes#51]
It would be nice to be able to build a log of changes since a specific release up until the latest HEAD.
The tool already supports "upcoming changes", but as far as I can tell it's not possible to retrieve these when using the `--between-tags` option.

Some possible solutions could be to use `--between-tags 2.0.4...HEAD` or to have a `--since-tag` option.

**Comment by rodrigok** [comment]
You can use `--for-tag upcoming`
