### ISSUE TITLE
shorthand instead of shitty too much flags

### ISSUE THREAD

**Issue by tunnckoCore** [lalitkapoor/github-changes#54]
I have lib for this one, https://github.com/tunnckoCore/parse-github-short-url

This will allow us to do

``` js
github-changes tunnckoCore/parse-function#dev -f CHANGELOG.md -t MY_TOKEN
```

where `dev` is the `dev` branch, you know :)
Also add default for the `file` option, to be CHANGELOG.md

Previous year I also thought for project like this and started, locally, but don't have time to finish it.
It can be a much simpler and better approach: just execute git log programmatically 1) parse it, 2) pass it to some template engine with default template, 3) do request to Github API only for PRs and only if wanted.

**Comment by lalitkapoor** [comment]
I don't think it's too complicated to use the flags and I don't see a need to call it shitty. Im open to reviewing a pull request that deprecates the owner, repo, and branch tags and uses this tool.
