### ISSUE TITLE
Lost pull request who used "Squash and merge"

### ISSUE THREAD

**Issue by 304NotModified** [lalitkapoor/github-changes#60]
Thanks for this great tool!

Too bad PRs that are merged with "Squash and merge" are not outputted in the changelog. Is this something that could be fixed?

Using the following command:

`github-changes -o nlog -r nlog -a --only-pulls --use-commit-body`

e.g. this one is missing:
https://github.com/NLog/NLog/pull/1628

when using `github-changes -o nlog -r nlog -a --use-commit-body` (no `--only-pulls`) is somewhat there:

```
- [1bc8400](https://github.com/NLog/NLog/commit/1bc84001f3eab6175948bffd24168bb01048fc19) allow different separator for Exception.Data (#1628) (@FroggieFrog)
```

**Comment by lalitkapoor** [comment]
@304NotModified would you mind giving this a try and let me know if it works for you? - https://github.com/lalitkapoor/github-changes/pull/62

**Comment by 304NotModified** [comment]
@lalitkapoor 

Sorry for the delay.

I have tested, and unfortunately it won't work :(

Command I have executed:

```
github-changes -o nlog -r nlog -a --only-pulls --use-commit-body --date-format (YYYY/MM/DD)  
```

Pull request https://github.com/NLog/NLog/pull/1683  is missing (in non of the changes), it's squashed merged with commit https://github.com/NLog/NLog/commit/70bb5cf3bb412555e3aa78cdc33484a23a4dc214

**Comment by 304NotModified** [comment]
What are we trying to test with this regex on the commit message? `#12`  or `(#12)`?

`  isPull = /^.*\s\(\#\d+\)(\n+.*)?$/i.test(commit.commit.message);` 

it think it should test `Merge pull request #12`

so

`  isPull = /^.*\s*Merge pull request\s*\#\d+(\n+.*)?$/i.test(commit.commit.message);` 



https://regex101.com/r/y3r7qm/1

![image](https://cloud.githubusercontent.com/assets/5808377/20076516/fd77e84a-a538-11e6-81bb-7393a62c3933.png)

**Comment by 304NotModified** [comment]
any idea how to install the script with NPM while it's not in master? (for your PR I have merged it into my fork (master) and installed that one - confirmed it installed well by changing the version number)

**Comment by lalitkapoor** [comment]
@304NotModified you can just point the package to a git branch and it should take care of that. check out - http://stackoverflow.com/questions/17509669/how-to-install-nodejs-package-from-github-directly

**Comment by 304NotModified** [comment]
I guess my own regex would not work as `Merge pull request` is [already tested](https://github.com/lalitkapoor/github-changes/blob/344b0f27a18d1c469f746a638143c53237642ea6/bin/index.js#L395)

**Comment by 304NotModified** [comment]
my regex was wrong, new test:

https://regex101.com/r/y3r7qm/4

**Comment by 304NotModified** [comment]
I see the mistake, `(@FroggieFrog)` isn't in the commit message.

Fixed and tested: https://github.com/lalitkapoor/github-changes/pull/64

**Comment by lalitkapoor** [comment]
discussion continues in #64
