### ISSUE TITLE
Changed login info for GitHub -- fails instead of prompting for new password

### ISSUE THREAD

**Issue by sshorkey** [lalitkapoor/github-changes#63]
I was using this module with the -a option. The first time I used it, I entered my username and password the first time and after that it just worked. But I recently changed my password and now I get errors whenever I attempt to use this module. Instead of simply asking me for a new password, it just keeps giving me errors. How do I reset the authorizations?

I tried uninstalling this module and reinstalling it again, and even then, it still keeps trying to use the old login and failing each time. Where is that info being stored and why is it persisting after I remove the module? How can I delete this file to reset it?

**Comment by lalitkapoor** [comment]
I believe it is persisted to the `~/.config/` directory @sshorkey I'm using the ghauth library to take care of that bit: https://github.com/rvagg/ghauth
