### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by igitur** [lalitkapoor/github-changes#66]
I'm behind a corporate proxy and can't get this to work. 

I've tried digging into the dependencies. Seems `hyperquest` (via `ghauth`) struggles with a proxy, but even after fixing that, the other libraries also fail. I eventually accepted defeat.

**Comment by lalitkapoor** [comment]
@igitur can you give https://www.npmjs.com/package/global-tunnel a try?

**Comment by igitur** [comment]
Ok, I can try, but where should I use it?

**Comment by igitur** [comment]
Yeah, thanks, dude.

**Comment by lalitkapoor** [comment]
@igitur Is this still unresolved for you? I was cleaning up some old issues. Didi @a-hat's approach work for you?
