### ISSUE TITLE
Maximum call stack size exceeded when fetching commits

### ISSUE THREAD

**Issue by luizkowalski** [lalitkapoor/github-changes#70]
I'm trying to update my CHANGELOG and I'm seeing this error:

```javascript
fetched 8600 commits
fetched 8700 commits
fetched all commits
error RangeError: Maximum call stack size exceeded
    at getAllReachableCommits (/usr/local/lib/node_modules/github-changes/bin/index.js:1:1)
    at /usr/local/lib/node_modules/github-changes/bin/index.js:367:14
    at Array.forEach (<anonymous>)
    at getAllReachableCommits (/usr/local/lib/node_modules/github-changes/bin/index.js:364:31)
```

not sure what is going on, it is the first time I'm seeing this and I haven't changed anything

**Comment by lalitkapoor** [comment]
Hi @luizkowalski Can you please take a look at the following and see if you're able to help debug what's going on with your repo? https://github.com/lalitkapoor/github-changes/pull/68 This would be the second reported incident of this happening. I believe it's something specific to the way commits are linked in the repo, maybe an edge case I am not accounting for perhaps.

**Comment by luizkowalski** [comment]
hey @lalitkapoor 
I changed the script, as you can see here: https://github.com/luizkowalski/github-changes

I don't see the error anymore, but nothing happens after the `fetched all commits` message.

**Comment by lalitkapoor** [comment]
closing for now, can re-open if there are more instances of this occurring for others.
