### ISSUE TITLE
might be able to accomplish without having to hit the api

### ISSUE THREAD

**Issue by lalitkapoor** [lalitkapoor/github-changes#8]
This issue is pretty much a note to self.

When I clean up and restructure the code explore if doing everything (or most of it) locally is an option - most likely the repo is already cloned anyway. This way we don't need to hit the api to get all the information AND we have access to more functionality via the git cli tool.

Btw, if we need to generate a changelog for a private repository that we don't have access to - then we can just use the auth token supplied by the user to clone the repo. This is explained here - https://help.github.com/articles/git-over-https-using-oauth-token.

**Comment by rustybailey** [comment]
This would be awesome. I'm having a weird issue where I am able to auth on one machine, but not another. It would be great to bypass that entirely by using the information available in the local repo.

**Comment by lalitkapoor** [comment]
@rustybailey thanks for the feedback. It's a known issue - https://github.com/lalitkapoor/github-changes/issues/44 I'll get it fixed up.

**Comment by andrewholgate** [comment]
This makes a lot of sense.

It would also be an improvement as it would also work in a normal development workflow where you want to push the latest `CHANGELOG.md` as part of the current commit changes (such as a new tag on the `master`). If it uses the api as a reference you need to push the latest commit + tag first and then only afterwards are you able to generate the new `CHANGELOG.md`.

Unless there'something I'm missing here?

**Comment by lalitkapoor** [comment]
@andrewholgate I agree, it would be nice to have that. I have to see if it's possible to maintain the same formatting. One thing I know that I'll have to work through is being able to give attribution to the github users involved in a PR (using their github names).

To answer your second part about having to have an additional commit. This is what I do to avoid that: https://github.com/lalitkapoor/github-changes/blob/master/release.sh#L11-L14
